Use matrix build strategy to build in parallel, isolate errors

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -8,6 +8,12 @@ env:
   strDefaultGtestOutput: "test_detail.xml"
 jobs:
   test-in-windows:
+    strategy:
+      matrix:
+        arch: [x86, x64]
+        cc: [msvc, llvm]
+        std: [c++14, c++17, c++20]
+        opt: [nope, max]
     runs-on: windows-latest
     defaults: 
         run:
@@ -46,74 +52,67 @@ jobs:
             'gdi32.lib'
             'user32.lib'
           );
-          
+
           $pathMSBuild = vswhere -products * -requires Microsoft.Component.MSBuild -property installationPath -latest;
-          @( 'x86', 'x64' ) | % { $strArch=$_; 
-            if ( 'x64' -eq $strArch ) {
-              $path = join-path $pathMSBuild 'VC/Auxiliary/Build/vcvars64.bat';
-            }
-            else {
-              $path = join-path $pathMSBuild 'VC/Auxiliary/Build/vcvars32.bat';
-            }
-            ; # @insp https://github.com/microsoft/vswhere/wiki/Find-VC
-            cmd /s /c """$path"" $args && set" | where { $_ -match '(\w+)=(.*)' } | foreach {
-              $null = new-item -force -path "Env:\$($Matches[1])" -value $Matches[2];
-            }
-          @( 'msvc', 'llvm' ) | % { $strToolSet=$_; 
-          @( '/std:c++14', '/std:c++17', '/std:c++20' ) | % { $strCppVer=$_;
-          @( 'nope', 'max' ) | % { $strOptimize=$_;
-            if ( 'msvc' -eq $strToolSet ) {
-              $exe = 'cl';
-              $building = '/MP ';
-              if ( 'max' -eq $strOptimize ) {
-                $building += " /Gy /O2 /GL ";
-              }
-            } elseif ( 'llvm' -eq $strToolSet ) {
-              $exe = 'clang-cl';
-              $building = '-Wno-ignored-pragma-optimize -Wno-microsoft-include -Wno-microsoft-cast -fms-compatibility -fms-extensions ';
-              if ( 'x86' -eq $strArch ) {
-                $building += " -m32 ";
-              }
-              if ( 'max' -eq $strOptimize ) {
-                $building += " /Gy /O2 -flto -fuse-ld=lld ";
-              }
-            }
-            $building += ('' +
-              " /EHsc /nologo " +
-              " $strCppVer " +
-              " /I""../include"" /I""${{ env.strDirGTest }}/googletest/include"" /I""${{ env.strDirGTest }}/googletest"" /I""${{ env.strDirGTest }}/googlemock/include"" /I""${{ env.strDirGTest }}/googlemock"" " +
-              " ""../src/${{ env.strFirstObj }}.cpp"" " +
-              " ""${{ env.strDirGTest }}/googletest/src/gtest-all.cc"" " +
-              " ""${{ env.strDirGTest }}/googlemock/src/gmock-all.cc"" " +
-              ( $arrSources -join ' ' ) +
-              " /link " +
-              ( $arrLibs -join ' ' ) +
-              " /machine:$strArch " + 
-              '')
-            ; # for linker
-            if ( ( 'msvc' -eq $strToolSet ) -And ( 'max' -eq $strOptimize ) ) {
-              $building += " /LTCG:incremental ";
-            }
-            echo "strArch=$strArch, strCppVer=$strCppVer, strOptimize=$strOptimize, exe=$exe";
-            $process = Start-Process $exe -ArgumentList $building -Wait -NoNewWindow -PassThru;
-            echo $process.ExitCode;
-            $failures = 'undefined';
-            $errors = 'undefined';
-            if ( 0 -eq $process.ExitCode ) {
-              Start-Process "${{ env.strFirstObj }}.exe" -ArgumentList "--gtest_output=xml" -Wait;
-              [xml]$oSystem_Xml_XmlDocument = Get-Content "${{ env.strDefaultGtestOutput }}";
-              $oSystem_Xml_XmlElement = $oSystem_Xml_XmlDocument.GetElementsByTagName( 'testsuites' ).Item( 0 );
-              $failures = $oSystem_Xml_XmlElement.GetAttribute( 'failures' );
-              $errors = $oSystem_Xml_XmlElement.GetAttribute( 'errors' );
-              Remove-Item -Path "${{ env.strFirstObj }}.exe";
-              Remove-Item -Path "${{ env.strDefaultGtestOutput }}";
-            }
-            echo "gtest_failures=$failures";
-            echo "gtest_errors=$errors";
+
+          if ( 'x64' -eq ${{ matrix.arch }} ) {
+            $path = join-path $pathMSBuild 'VC/Auxiliary/Build/vcvars64.bat';
           }
+          else {
+            $path = join-path $pathMSBuild 'VC/Auxiliary/Build/vcvars32.bat';
           }
+          ; # @insp https://github.com/microsoft/vswhere/wiki/Find-VC
+          cmd /s /c """$path"" $args && set" | where { $_ -match '(\w+)=(.*)' } | foreach {
+            $null = new-item -force -path "Env:\$($Matches[1])" -value $Matches[2];
           }
+
+          if ( 'msvc' -eq ${{ matrix.cc }} ) {
+            $exe = 'cl';
+            $building = '/MP ';
+            if ( 'max' -eq ${{ matrix.opt }} ) {
+              $building += " /Gy /O2 /GL ";
+            }
+          } elseif ( 'llvm' -eq ${{ matrix.cc }} ) {
+            $exe = 'clang-cl';
+            $building = '-Wno-ignored-pragma-optimize -Wno-microsoft-include -Wno-microsoft-cast -fms-compatibility -fms-extensions ';
+            if ( 'x86' -eq ${{ matrix.arch }} ) {
+              $building += " -m32 ";
+            }
+            if ( 'max' -eq ${{ matrix.opt }} ) {
+              $building += " /Gy /O2 -flto -fuse-ld=lld ";
+            }
           }
+          $building += ('' +
+            " /EHsc /nologo " +
+            " /std:${{ matrix.std }} " +
+            " /I""../include"" /I""${{ env.strDirGTest }}/googletest/include"" /I""${{ env.strDirGTest }}/googletest"" /I""${{ env.strDirGTest }}/googlemock/include"" /I""${{ env.strDirGTest }}/googlemock"" " +
+            " ""../src/${{ env.strFirstObj }}.cpp"" " +
+            " ""${{ env.strDirGTest }}/googletest/src/gtest-all.cc"" " +
+            " ""${{ env.strDirGTest }}/googlemock/src/gmock-all.cc"" " +
+            ( $arrSources -join ' ' ) +
+            " /link " +
+            ( $arrLibs -join ' ' ) +
+            " /machine:${{ matrix.arch }} " + 
+            '')
+          ; # for linker
+          if ( ( 'msvc' -eq ${{ matrix.cc }} ) -And ( 'max' -eq ${{ matrix.opt }} ) ) {
+            $building += " /LTCG:incremental ";
+          }
+          echo "arch=${{ matrix.arch }}, cc=${{ matrix.cc }} std=${{ matrix.std }}, optimize=${{ matrix.opt }}, exe=$exe";
+          $process = Start-Process $exe -ArgumentList $building -Wait -NoNewWindow -PassThru;
+          echo $process.ExitCode;
+          $failures = 'undefined';
+          $errors = 'undefined';
+          if ( 0 -eq $process.ExitCode ) {
+            $process = Start-Process "${{ env.strFirstObj }}.exe" -ArgumentList "--gtest_output=xml" -Wait;
+            [xml]$oSystem_Xml_XmlDocument = Get-Content "${{ env.strDefaultGtestOutput }}";
+            $oSystem_Xml_XmlElement = $oSystem_Xml_XmlDocument.GetElementsByTagName( 'testsuites' ).Item( 0 );
+            $failures = $oSystem_Xml_XmlElement.GetAttribute( 'failures' );
+            $errors = $oSystem_Xml_XmlElement.GetAttribute( 'errors' );
+          }
+          echo "gtest_failures=$failures";
+          echo "gtest_errors=$errors";
+          exit $process.ExitCode
 
       - name: If success
         if: ${{ success( ) }}
